### PR TITLE
Acknowledge Nixpkgs package

### PR DESCRIPTION
**Pull request by RPGHank**
Adds NixOS badge and link to Nixpkgs file

### CODE REVIEW

**Comment by RPGHank** [comment]
Alternatively the link could be to the [NixOS package search result](https://search.nixos.org/packages?channel=20.09&show=whatsapp-for-linux&from=0&size=50&sort=relevance&query=whatsapp)

**Comment by eneshecan** [comment]
Hi, thanks a lot for this!

> Alternatively the link could be to the [NixOS package search result](https://search.nixos.org/packages?channel=20.09&show=whatsapp-for-linux&from=0&size=50&sort=relevance&query=whatsapp-for-linux)

I think this would be better since redirecting to github is not very desirable.

And please keep in mind that you agree to take the responsibility to update this package when there is a new release since we don't want to show a package in the readme which is not maintained.

**Comment by RPGHank** [comment]
> And please keep in mind that you agree to take the responsibility to update this package when there is a new release since we don't want to show a package in the readme which is not maintained

The current maintainer, @wandersoncferreira, hasn't updated the package to 1.1.6 yet and unfortunately I am not capable of packaging Nixpkgs :/

It might be best to close this PR then

**Comment by eneshecan** [comment]
Maybe we can ask him here? @wandersoncferreira seems to be the maintainer.

**Pull request closed without merging**
