### PR TITLE
Design change proposal

### PR DESCRIPTION
**Pull request by juxuanu**
Hi again, if you have time take a look at what I propose here. 

Right now is throwing me `terminate called after throwing an instance of 'Gtk::BuilderError'` and I'm scratching my head around this. But you should be able to check the code and the design with Glade.

It is inspired from https://github.com/eneshecan/whatsapp-for-linux/issues/41

### CODE REVIEW

**Comment by eneshecan** [comment]
Hello, I'll try this, thank you for your efforts :) At a very first glance, I see some unrelated changes other than design. About the error, I can only suggest cleaning and rebuilding again. Since ui files are being embedded into executable, you need to trigger the build again to get the up to date ui resources. I think it's a good idea to add this to readme.

**Comment by juxuanu** [comment]
Yes, there is other work too. If you can help me out with this it'd be better. I'm quite new with Glade and Gtk and I don't know what to do with this at the moment. If you want, of course :)
About the error, I already do `make clean all` but with no luck.

**Comment by eneshecan** [comment]
Of course, I'll have a look when I have some time :)

**Comment by eneshecan** [comment]
Hi, I just checked the code. I believe it crashes because it needs libhandy as a dependency which is for mobile phones. The good news is, I just tried to remove that and used a `GtkHeaderBar` instead of `HdyHeaderBar` and it runs. Well, I guess you will handle the rest like opening the popover when clicked to the global menu button. Overall, I kind of liked this idea :) Please let me know when you are finished with your implementation.

**Comment by eneshecan** [comment]
Also, you need to use `signal_clicked` for "menu buttons" since they are just buttons now.

**Comment by juxuanu** [comment]
I will work this with your indications, thank you.

**Comment by eneshecan** [comment]
I merged #46 and we don't need this anymore but Thank you for the idea and all the effort :1st_place_medal:

**Pull request closed without merging**
