### PR TITLE
Update debian packaging

### PR DESCRIPTION
**Pull request by fvcr**

### CODE REVIEW

**Comment by eneshecan** [comment]
Hi @fvcr. Thank you for this. You can keep yourself in the maintainers. However, could you please tell me what are the improvements and idea behind this? I also see that you removed the automatic versioning mechanism which we implemented to not have to change several version strings along with the project when we increase the version.

**Comment by fvcr** [comment]
Hello,
Thanks for looking at this.

Answering your question,
> However, could you please tell me what are the improvements and idea behind this?

My idea is to get the debian package in good condition and allow someone else to build it, note that in [README.md](https://github.com/eneshecan/whatsapp-for-linux/blob/6469b0be6eae8c3825786276d62ebb29e3598875/README.md) you mention:
> Run ```dpkg-buildpackage -uc -us -ui```.

However, the package is not built.

About that:
> I also see that you removed the automatic versioning mechanism which we implemented to not have to change several version strings along with the project when we increase the version.

It was necessary to modify it in order to build the package.
As well as modifying [debian/control](https://github.com/eneshecan/whatsapp-for-linux/pull/112/commits/a5bd6920814a8592b389157fe6c8ac03770c7a5b) to allow the package to be built, for example by adding Build-Depends.

But, of course, these were just suggestions... feel free to reject them or not.

Best Regards.

**Comment by eneshecan** [comment]
Could you please tell me what error you get when you try to build? We shouldn't easily give up automatic versioning. Once we are sure to keep that or not, I will make a thorough review and try to build.

**Comment by fvcr** [comment]
I build the package in a chroot environment,
so basically I perform the following steps:

I download the tarball and extract it:
```
$ wget -c https://github.com/eneshecan/whatsapp-for-linux/archive/refs/tags/v1.1.7.tar.gz;
$ tar xvf v1.1.7.tar.gz
```
After that, I go into the whatsapp-for-linux-1.1.7:
```
$ cd whatsapp-for-linux-1.1.7/
```
Then I will prepare the upstream source for Debian packaging with dh_make:
```
$ dh_make -f ../v1.1.7.tar.gz -c gpl3
```
Finally, I run dpkg-buildpackage:
```
$ dpkg-buildpackage
dpkg-buildpackage: info: source package whatsapp-for-linux
dpkg-buildpackage: info: source version 0
dpkg-buildpackage: info: source distribution stable
dpkg-buildpackage: info: source changed by Enes Hecan <nshecan@gmail.com>
dpkg-buildpackage: info: host architecture amd64
 dpkg-source --before-build .
 fakeroot debian/rules clean
cat: src/VERSION: No such file or directory
Setting version to 
debian/rules: line 8: fg: no job control
   dh_clean
 dpkg-source -b .
dpkg-source: warning: whatsapp-for-linux-1.1.7/debian/changelog(l1): badly formatted heading line
LINE: whatsapp-for-linux () stable; urgency=medium
dpkg-source: warning: whatsapp-for-linux-1.1.7/debian/changelog(l2): found blank line where expected first heading
dpkg-source: warning: whatsapp-for-linux-1.1.7/debian/changelog(l3): found change data where expected first heading
LINE:   * See https://github.com/eneshecan/whatsapp-for-linux/releases
dpkg-source: warning: unknown information field '' in input data in parsed version of changelog
dpkg-source: warning: no source format specified in debian/source/format, see dpkg-source(1)
dpkg-source: error: source package has two conflicting values - whatsapp-for-linux and unknown
dpkg-buildpackage: error: dpkg-source -b . subprocess returned exit status 2
```

I understand the reason for not building,
My changes to the package are to make it possible to build using dpkg-buildpackage,
without building cmake first.

But no problem, it was just a suggestion,
I understand that you prefer to build cmake before generating any packages.

**Comment by eneshecan** [comment]
I am closing this PR but know that it helped me a lot to improve our packaging. Thanks a lot!

**Pull request closed without merging**
